app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::controller('auth/password', 'Auth\PasswordController', [
	'getEmail' => 'auth.password.email',
	'getReset' => 'auth.password.reset'
	]);

Route::controller('auth', 'Auth\AuthController', [
	'getLogin' => 'auth.login',
	'getLogout' => 'auth.logout'
	]);

Route::get('backend/users/{users}/confirm', ['as' => 'backend.users.confirm', 'uses' => 'Backend\UsersController@confirm']);
Route::resource('backend/users', 'Backend\UsersController', ['except' => ['show']]);

Route::get('backend/pages/{pages}/confirm', ['as' => 'backend.pages.confirm', 'uses' => 'Backend\PagesController@confirm']);
Route::resource('backend/pages', 'Backend\PagesController', ['except' => ['show']]);

Route::get('backend/dashboard', ['as' => 'backend.dashboard', 'uses' => 'Backend\DashboardController@index']);

Route::get('/', function () {
    return view('welcome');
});

app/Http/Controllers/Backend/Controller.php
<?php

namespace LaraCms\Http\Controllers\Backend;

use Illuminate\Routing\Controller as BaseController;

abstract class Controller extends BaseController
{
	
	public function __construct()
	{
		$this->middleware('auth');
	}
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace LaraCms\Http\Controllers\Backend;

class DashboardController extends Controller
{
	public function index()
	{
		return view('backend.dashboard');
	}
}

app/Http/Controllers/Backend/PagesController.php
<?php

namespace LaraCms\Http\Controllers\Backend;

use LaraCms\Page;

use Illuminate\Http\Request;

use LaraCms\Http\Requests;

class PagesController extends Controller
{   
    protected $pages;

    public function __construct(Page $pages)
    {
        $this->pages = $pages;

        parent::__construct();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pages = $this->pages->all();

        return view('backend.pages.index', compact('pages'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Page $page)
    { 
        $templates = $this->getPageTemplate();

        return view('backend.pages.form', compact('page', 'templates'));        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Requests\StorePageRequest $request)
    {
        $this->pages->create($request->only('title', 'uri', 'name', 'content', 'template'));

        return redirect(route('backend.pages.index'))->with('status', 'Page has been created');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $page = $this->pages->findOrFail($id);

        $templates = $this->getPageTemplate();
       
        return view('backend.pages.form', compact('page', 'templates'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Requests\UpdatePageRequest $request, $id)
    {
        $page = $this->pages->findOrFail($id);

        $page->fill($request->only('title', 'uri', 'name', 'content', 'template'))->save();
        
        return redirect(route('backend.pages.edit', $page->id))->with('status', 'Page has been updated');
    }

    public function confirm($id)
    {
         $page = $this->pages->findOrFail($id);

        return view('backend.pages.confirm', compact('page'));
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $page = $this->pages->findOrFail($id);

        $page->delete();

        return redirect(route('backend.pages.index'))->with('status', 'Page has been deleted');
    }


    protected function getPageTemplate()
    {
        $templates =  config('cms.templates');
        
        return ['' => ''] + array_combine(array_keys($templates),array_keys($templates));
    }
}

app/Http/Controllers/Backend/UsersController.php
<?php

namespace LaraCms\Http\Controllers\Backend;

use LaraCms\User;
use Illuminate\Http\Request;

use LaraCms\Http\Requests;

class UsersController extends Controller
{

    protected $users;

    public function __construct(User $users)
    {
        $this->users = $users;

        parent:: __construct(); 
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $users = $this->users->paginate(10);

       return view('backend.users.index', compact('users')); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(User $user)
    {
        return view('backend.users.form', compact('user'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Requests\StoreUserRequest $request)
    {
        $this->users->create($request->only('name', 'email', 'password'));

        return redirect(route('backend.users.index'))->with('status', 'User has been created'); 
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = $this->users->findOrFail($id);

        return view('backend.users.form', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    
    public function update(Requests\UpdateUserRequest $request, $id)
    {
        $user = $this->users->findOrFail($id);

        $user->fill($request->only('name', 'email', 'password'))->save();

        return redirect(route('backend.users.edit', $user->id))->with('status', 'User has been updated.');
    }

    public function confirm(Requests\DeleteUserRequest $request, $id)
    {
        $user = $this->users->findOrFail($id);

        return view('backend.users.confirm', compact('user'));
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Requests\DeleteUserRequest $request, $id)
    {
        $user = $this->users->findOrFail($id);

        $user->delete();

        return redirect(route('backend.users.index'))->with('status', 'User has been deleted');
    }
}

resources/views/backend/pages/confirm.blade.php
@extends('layouts.backend')

@section('title', 'Delete '.$page->title)

@section('content')
	{!! Form::open(['method' => 'delete', 'route' => ['backend.pages.destroy', $page->id]]) !!}
		<div class="alert alert-danger">
			<strong>Warning!</strong> You are going to delete this page.
		</div>

		{!! Form::submit('Yes, delete this page!', ['class' => 'btn btn-danger']) !!}

		<a href="{{ route('backend.pages.index') }}" class="btn  btn-success">
			<strong> Go back!!</strong>
		</a>
	{!! Form::close() !!}
@endsection

resources/views/backend/pages/form.blade.php
@extends('layouts.backend')

@section('title', $page->exists ? 'Editing '.$page->title :'Create New Page')

@section('content')
	{!! Form::model($page,[
		'method' => $page->exists ? 'put' : 'post',
		'route' => $page->exists ? ['backend.pages.update', $page->id] : ['backend.pages.store']
	]) !!}

		<div class="form-group">
			{!! Form::label('title') !!}
			{!! Form::text('title', null, ['class' => 'form-control']) !!}
		</div>

		<div class="form-group">
			{!! Form::label('uri', 'URI') !!}
			{!! Form::text('uri', null, ['class' => 'form-control']) !!}
		</div>

		<div class="form-group">
			{!! Form::label('name') !!}
			{!! Form::text('name', null, ['class' => 'form-control']) !!}
			
			<p class="help-block">
				This name is used to generate links to the page.
			</p>
		</div>

		<div class="form-group row">
			<div class="col-md-12">
				{!! Form::label('template') !!}
			</div>
			<div class="col-md-4">
				{!! Form::select('template', $templates, null, ['class' => 'form-control']) !!}
			</div>
		</div>

		<div class="form-group">
			{!! Form::label('content') !!}
			{!! Form::textarea('content', null, ['class' => 'form-control']) !!}
		</div>

		{!! Form::submit($page->exists ? 'Save page' : 'Create New Page', ['class' => 'btn btn-primary']) !!}
	{!! Form::close() !!}

	<script>
		new SimpleMDE().render();
	</script>
@endsection

resources/views/backend/pages/index.blade.php
@extends('layouts.backend')

@section('title', 'Pages')

@section('content')
	<a href="{{ route('backend.pages.create') }}" class="btn btn-primary">Create New Page</a>
	<table class="table table-hover">
		<thead>
			<tr>
				<td>Title</td>
				<td>URI</td>
				<td>Name</td>
				<td>Template</td>
				<td>Edit</td>
				<td>Delete</td>
			</tr>
		</thead>
		<tbody>
			@if($pages->isEmpty())
				<tr>
					<td colspan="5" align="center">There are no pages.</td>
				</tr>
			@else
				@foreach($pages as $page)
					<tr>
						<td>
							<a href="{{ route('backend.pages.edit', $page->id) }}">
								{{$page->title}}
							</a>
						</td>
						<td>
							<a href="{{ url($page->uri)}}">
								{{ '/'.ltrim($page->uri,'/') }}
							</a>
						</td>
						<td>
							{{$page->name or 'None'}}
						</td><td>
							{{$page->template or 'None'}}
						</td>
						<td>
							<a href="{{ route('backend.pages.edit', $page->id) }}">
								<span class="glyphicon glyphicon-edit"></span>
							</a>
						</td>
						<td>
							<a href="{{ route('backend.pages.confirm', $page->id) }}">
								<span class="glyphicon glyphicon-remove"></span>
							</a>
						</td>
					</tr>
				@endforeach
			@endif
		</tbody>
	</table>
@endsection