app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::controller('auth/password', 'Auth\PasswordController', [
	'getEmail' => 'auth.password.email',
	'getReset' => 'auth.password.reset'
	]);

Route::controller('auth', 'Auth\AuthController', [
	'getLogin' => 'auth.login',
	'getLogout' => 'auth.logout'
	]);

Route::get('backend/users/{users}/confirm', ['as' => 'backend.users.confirm', 'uses' => 'Backend\UsersController@confirm']);
Route::resource('backend/users', 'Backend\UsersController', ['except' => ['show']]);

Route::get('backend/pages/{pages}/confirm', ['as' => 'backend.pages.confirm', 'uses' => 'Backend\PagesController@confirm']);
Route::resource('backend/pages', 'Backend\PagesController', ['except' => ['show']]);

Route::get('backend/dashboard', ['as' => 'backend.dashboard', 'uses' => 'Backend\DashboardController@index']);

Route::get('/', function () {
    return view('welcome');
});

app/User.php
<?php

namespace LaraCms;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract,
                                    AuthorizableContract,
                                    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'email', 'password'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];

    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = bcrypt($value);
    }
}

app/Http/Controllers/Backend/Controller.php
<?php

namespace LaraCms\Http\Controllers\Backend;

use Illuminate\Routing\Controller as BaseController;

abstract class Controller extends BaseController
{
	
	public function __construct()
	{
		$this->middleware('auth');
	}
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace LaraCms\Http\Controllers\Backend;

class DashboardController extends Controller
{
	public function index()
	{
		return view('backend.dashboard');
	}
}

app/Http/Controllers/Backend/PagesController.php
<?php

namespace LaraCms\Http\Controllers\Backend;

use LaraCms\Page;

use Illuminate\Http\Request;

use LaraCms\Http\Requests;

class PagesController extends Controller
{   
    protected $pages;

    public function __construct(Page $pages)
    {
        $this->pages = $pages;

        parent::__construct();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pages = $this->pages->all();

        return view('backend.pages.index', compact('pages'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Page $page)
    { 
        $templates = $this->getPageTemplate();

        return view('backend.pages.form', compact('page', 'templates'));        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Requests\StorePageRequest $request)
    {
        $this->pages->create($request->only('title', 'uri', 'name', 'content', 'template'));

        return redirect(route('backend.pages.index'))->with('status', 'Page has been created');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $page = $this->pages->findOrFail($id);

        $templates = $this->getPageTemplate();
       
        return view('backend.pages.form', compact('page', 'templates'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Requests\UpdatePageRequest $request, $id)
    {
        $page = $this->pages->findOrFail($id);

        $page->fill($request->only('title', 'uri', 'name', 'content', 'template'))->save();
        
        return redirect(route('backend.pages.edit', $page->id))->with('status', 'Page has been updated');
    }

    public function confirm($id)
    {
         $page = $this->pages->findOrFail($id);

        return view('backend.pages.confirm', compact('page'));
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $page = $this->pages->findOrFail($id);

        $page->delete();

        return redirect(route('backend.pages.index'))->with('status', 'Page has been deleted');
    }


    protected function getPageTemplate()
    {
        $templates =  config('cms.templates');
        
        return ['' => ''] + array_combine(array_keys($templates),array_keys($templates));
    }
}

app/Http/Controllers/Backend/UsersController.php
<?php

namespace LaraCms\Http\Controllers\Backend;

use LaraCms\User;
use Illuminate\Http\Request;

use LaraCms\Http\Requests;

class UsersController extends Controller
{

    protected $users;

    public function __construct(User $users)
    {
        $this->users = $users;

        parent:: __construct(); 
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $users = $this->users->paginate(10);

       return view('backend.users.index', compact('users')); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(User $user)
    {
        return view('backend.users.form', compact('user'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Requests\StoreUserRequest $request)
    {
        $this->users->create($request->only('name', 'email', 'password'));

        return redirect(route('backend.users.index'))->with('status', 'User has been created'); 
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = $this->users->findOrFail($id);

        return view('backend.users.form', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    
    public function update(Requests\UpdateUserRequest $request, $id)
    {
        $user = $this->users->findOrFail($id);

        $user->fill($request->only('name', 'email', 'password'))->save();

        return redirect(route('backend.users.edit', $user->id))->with('status', 'User has been updated.');
    }

    public function confirm(Requests\DeleteUserRequest $request, $id)
    {
        $user = $this->users->findOrFail($id);

        return view('backend.users.confirm', compact('user'));
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Requests\DeleteUserRequest $request, $id)
    {
        $user = $this->users->findOrFail($id);

        $user->delete();

        return redirect(route('backend.users.index'))->with('status', 'User has been deleted');
    }
}

resources/views/backend/users/confirm.blade.php
@extends('layouts.backend')

@section('title', 'Delete '.$user->name)

@section('content')
	{!! Form::open(['method' => 'delete', 'route' => ['backend.users.destroy', $user->id]]) !!}
		<div class="alert alert-danger">
			<strong>Warning!</strong> You are going to delete this user.
		</div>

		{!! Form::submit('Yes, delete this user!', ['class' => 'btn btn-danger']) !!}

		<a href="{{ route('backend.users.index') }}" class="btn  btn-success">
			<strong> Go back!!</strong>
		</a>
	{!! Form::close() !!}
@endsection

resources/views/backend/users/form.blade.php
@extends('layouts.backend')

@section('title', $user->exists ? 'Editing'.$user->name : 'Create New User')

@section('content')
	{!! Form::model($user, [
		'method' => $user->exists ? 'put' : 'post',
		'route' => $user->exists ? ['backend.users.update', $user->id] : ['backend.users.store']
		]) !!}

	<div class="form-group">
		{!! Form::label('name') !!}
		{!! Form::text('name', null, ['class' => 'form-control']) !!}
	</div>

	<div class="form-group">
		{!! Form::label('email') !!}
		{!! Form::email('email', null, ['class' => 'form-control']) !!}
	</div>
	
	<div class="form-group">
		{!! Form::label('password') !!}
		{!! Form::password('password',  ['class' => 'form-control']) !!}
	</div>
	
	
	<div class="form-group">
		{!! Form::label('password_confirmation') !!}
		{!! Form::password('password_confirmation',  ['class' => 'form-control']) !!}
	</div>

	{!! Form::submit($user->exists ? 'Save User' : 'Create New User', ['class' => 'btn btn-primary'])!!}
@endsection

resources/views/backend/users/index.blade.php
@extends('layouts.backend')

@section('title', 'Users')

@section('content')
	<a href="{{ route('backend.users.create') }}" class="btn btn-primary">Create New User</a>
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Name</th>
				<th>E-mail</th>
				<th>Edit</th>
				<th>Delete</th>
			</tr>
		</thead>
		<tbody>
			@foreach($users as $user)
				<tr>
					<td>
						<a href="{{ route('backend.users.edit', $user->id) }}">{{ $user->name }}</a>
					</td>
					<td>{{ $user->email }}</td>
					<td>
						<a href="{{ route('backend.users.edit', $user->id) }}">
							<span class="glyphicon glyphicon-edit"></span>
						</a>
					</td>
					<td>
						<a href="{{ route('backend.users.confirm', $user->id) }}">
							<span class="glyphicon glyphicon-remove"></span>
						</a>
					</td>
				</tr>
			@endforeach
		</tbody>
	</table>

	{!! $users->render() !!}
@endsection